name: PR Build

defaults:
  run:
    shell: bash

on:
  pull_request:



jobs:
  build:
    name: Create/upload a file
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          # We need to get all branches and tags for git describe to work properly
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - run: tar -czf /tmp/files.tar.gz

      - name: Upload all artifacts
        uses: actions/upload-artifact@v3
        with:
          name: files.tar.gz
          path: /tmp/files.tar.gz


